# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monkey', '0002_auto_20190320_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='monkey',
            name='password',
            field=models.CharField(default='password', max_length=255),
            preserve_default=False,
        ),
    ]
